export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const LOAD_SESSIONS = "LOAD_SESSIONS";
export const LOAD_ONE_SESSION = "LOAD_ONE_SESSION";
export const REMOVE_SESSION = "REMOVE_SESSION";

export const LOAD_ACTIVITIES = "LOAD_ACTIVITIES";
export const LOAD_ONE_ACTIVITY = "LOAD_ONE_ACTIVITY";
export const REMOVE_ACTIVITY = "REMOVE_ACTIVITY";
